name: CI

on: [workflow_dispatch]

jobs:
  build:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a one-line script
      run: dir > dirlista.txt
    - name: asdddff
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
